name: Update Types

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update_types:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Bun
              uses: oven-sh/setup-bun@v1

            - name: Clone TBA Schema parser repo
              run: git clone https://github.com/ark0f/tg-bot-api.git

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Generate TBA Schema
              run: cd tg-bot-api && cargo run --package gh-pages-generator --bin gh-pages-generator -- dev

            - name: Get hash from schema
              run: bun cicd

            - name: Generate types
              run: bun generate

            - name: Commit and Push changes
              uses: EndBug/add-and-commit@v9
              with:
                  message: "chore(TBA): regenerate types and update hash"

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"
                  scope: "@gramio"

            - name: Publish package
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
